#!/bin/bash

. $HOME/.bashrc
. $HOME/.bashutils.rc

######################################################################
######################################################################
######################################################################
BASEDIR=${MPAD}
test -d ${BASEDIR} || ErrExit "directory ${BASEDIR} not found"

HTMLDIR=${BASEDIR}/_build/html
mkdir -p ${HTMLDIR}
cd ${HTMLDIR}
test "x${PWD}" == "x${HTMLDIR}" || ErrExit "could not cd to ${HTMLDIR}"

git add --all .
git commit -a -m"updates"
git push origin gh-pages
