#!/bin/bash

date > /tmp/sphinx.out
make html 2>&1 | tee -a /tmp/sphinx.out
PolishHTML.sh

##################################################
# forcing browser reload...
##################################################
ACTIVE=`xdotool getactivewindow`

wmctrl -pGl | grep 'meep_adjoint.*Chrom' | while read WID REST 
do 
  xdotool windowactivate --sync ${WID} key ctrl+r
done

xdotool windowactivate --sync ${ACTIVE} 
